-- =====================================================================
-- Ember Outpost (3/3) — Acts V (courtyard) + VI (sanctum) + VII (endings)
--                    + ALL story_edges
--                    + story_templates.root_node_id
-- =====================================================================

set search_path to dungeonku, public;

-- ---------------------------------------------------------------------
-- Remaining nodes
-- ---------------------------------------------------------------------

insert into story_nodes
  (id, template_id, type, body, speaker, speaker_profile, tags,
   on_enter_actions, ai_reskin_policy, sort_order)
values

-- ACT V — Inside the Outpost (courtyard hub)
('ember_outpost__courtyard', 'ember_outpost', 'scene',
 $b$The courtyard of the Ember Outpost is dust and trampled straw and the smell of burning resin. A red-and-black banner flutters from the keep's central spar. To one side is the barracks — long, low, smelling of wool and sweat. Past it, the chapel of the ember, with smoke rising from a vent in the roof. Across, the smithy, working — you can hear the conscript boy on the bellows. Behind the smithy is the kennel, and the smell from it is wrong. The inner door, which leads to the keep proper and the sanctum beyond, is closed.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_5", "hub", "replayable_actions"]$t$::jsonb,
 '[]'::jsonb, 'pivotal_only', 300),

-- Barracks
('ember_outpost__barracks_dialog', 'ember_outpost', 'dialog',
 $b$Two men in red leathers are dicing at a table near the door of the barracks. They look up when you enter, and one of them — the broader, with a scar that stops at the corner of his mouth — pushes back his stool, slowly. "Friend," he says. "I don't think I know you."$b$,
 'Watchman Beren',
 $sp$ {"tone":["careful","not-stupid","willing-to-be-fooled"], "default_mood":"alert"} $sp$::jsonb,
 $t$["act_5", "dialog_hub"]$t$::jsonb, '[]'::jsonb, 'never', 310),

('ember_outpost__barracks_pass', 'ember_outpost', 'transition',
 $b$You hold the man's eyes and tell him, calmly, that you are with the supply detail from the south fork. The lie is good and it lands; he relaxes back onto his stool, returns to his dice, and waves a hand without looking up. "Don't track mud through the chapel," he calls after you. "She hates that."$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"barracks_passed","value":true}}]$a$::jsonb,
 'never', 311),

('ember_outpost__barracks_combat', 'ember_outpost', 'combat',
 $b$Beren stands all the way up. The other man at the dice-table is already reaching for his belt. There is no good way out of this room except through them.$b$,
 null, '{}'::jsonb, $t$["act_5", "combat"]$t$::jsonb,
 $a$[{"kind":"start_combat","payload":{"enemy_set_id":"barracks_pair"}}]$a$::jsonb,
 'never', 312),

-- Chapel of the Ember
('ember_outpost__chapel_scene', 'ember_outpost', 'scene',
 $b$The chapel of the ember is darker than it should be at midday. A small flame burns in a basin of black iron at the front of the room, and the smoke that rises from it does not behave like smoke. The benches are simpler than the ones in Tarin's chapel, and there are only two. There is no altar, only the basin. On the wall behind the basin, in red paint, is one word in a language you do not know. The flame, when you look at it directly, makes you slightly less honest with yourself.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_5"]$t$::jsonb, '[]'::jsonb,
 'pivotal_only', 320),

('ember_outpost__chapel_pray', 'ember_outpost', 'transition',
 $b$You sit on one of the benches and try to pray as Tarin would. The flame in the basin flares, briefly, in a way that has nothing to do with any draft. You feel watched, but not unkindly. You sit longer than you meant to. When you stand, the small wound in your side that was beginning to ache has stopped aching.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"heal_player","payload":{"dice":"d6"}},{"kind":"set_flag","payload":{"key":"chapel_witnessed","value":true}}]$a$::jsonb,
 'never', 321),

('ember_outpost__chapel_desecrated', 'ember_outpost', 'transition',
 $b$You spit into the basin. The flame answers — it goes white-blue for a half-second, then sullen red, then back to ordinary fire. Somewhere in the keep above you, a single bell rings, once. You leave the chapel quickly. You feel watched now, and not kindly.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"desecrated_chapel","value":true}},{"kind":"set_flag","payload":{"key":"alarm_uncertain","value":true}}]$a$::jsonb,
 'never', 322),

('ember_outpost__chapel_clue', 'ember_outpost', 'transition',
 $b$You search the chapel without disturbing the basin. Behind one of the benches you find a folded paper with three names on it in a careful hand. The first two are crossed out. The third is the name "Edda" — and below that, in smaller letters, "Bren's sister, Ashbrook smithy, age 17 when taken." You fold the paper away. You know now what Vela was groping toward.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"knows_korr_real_name","value":true}}]$a$::jsonb,
 'pivotal_only', 323),

-- Smithy (inside the outpost)
('ember_outpost__smithy_scene', 'ember_outpost', 'scene',
 $b$The outpost's smithy is bigger than Bren's, and louder, and worse. A boy of perhaps fifteen is on the bellows, his face soot-streaked, his hands burnt in places that have not yet healed. He sees you and goes very still, and then, very deliberately, looks back down at the bellows-handle. There is no master smith in the room with him, only a half-finished spear-shaft on the bench and a stack of new spear-tips beside it. On the wall, blueprints — not for tools, but for something larger.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb, '[]'::jsonb, 'never', 330),

('ember_outpost__smithy_blueprints', 'ember_outpost', 'transition',
 $b$The blueprints on the wall are for a brazier-cart — an iron wagon with a fire-basin at its centre, designed to be drawn by oxen. There is a note in red ink: "for the great burning, third quarter." You understand now, in a small cold way, that the Order's ambition does not stop at Ashbrook. The Smithlight was first, and it was small. The next thing will not be small.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"knows_relic_use","value":true}}]$a$::jsonb,
 'pivotal_only', 331),

('ember_outpost__smithy_steal', 'ember_outpost', 'transition',
 $b$You take a small forge-pick and a folded leather of fine files and slip them into your pack while the boy on the bellows pointedly does not see you. He is breathing too carefully. You leave him to it.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"grant_item","payload":{"item_id":"forge_pick","qty":1}},{"kind":"set_flag","payload":{"key":"stole_tools","value":true}}]$a$::jsonb,
 'never', 332),

('ember_outpost__smithy_apprentice_dialog', 'ember_outpost', 'dialog',
 $b$The boy looks up from the bellows when you say his name — which Vela gave you. Tyne. He looks like a boy whose body has spent six weeks too far from his life. "Don't," he says, and then he says, "I'm sorry. Don't what. I don't know. Are you here for the lantern? Are you. Please tell me you are."$b$,
 'Apprentice Tyne',
 $sp$ {"tone":["frightened","exhausted","brave-around-the-edges"], "default_mood":"hopeful-and-afraid"} $sp$::jsonb,
 $t$["pivotal", "act_5", "dialog_hub"]$t$::jsonb, '[]'::jsonb, 'pivotal_only', 333),

('ember_outpost__apprentice_friend', 'ember_outpost', 'dialog',
 $b$Tyne looks at the forge-hammer in your hand — Bren's father's hammer — and his face does a thing that is not exactly relief and not exactly grief. He wipes his face with the back of his arm. "She let you take it. Then she's all right. Then —" he stops, swallows, nods. "There's a hidden bolt on the inner door. Eastern jamb, two hands above the latch. The Commander doesn't know about it. The old Watchman who showed it to me is dead now." He pauses. "Take me with you, when you go."$b$,
 'Apprentice Tyne',
 $sp$ {"tone":["frightened","relieved","decisive"]} $sp$::jsonb,
 $t$["pivotal", "act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"apprentice_help","value":true}}]$a$::jsonb,
 'pivotal_only', 334),

('ember_outpost__apprentice_silenced', 'ember_outpost', 'transition',
 $b$You make sure Tyne will not call out. You will think about how you did that, later, when there is time. He does not bleed, much. You leave him under the workbench and walk on. Some part of you will not put this down for a long time.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"silenced_apprentice","value":true}}]$a$::jsonb,
 'never', 335),

-- Kennel
('ember_outpost__kennel_choice', 'ember_outpost', 'scene',
 $b$The kennel is a long shed of black timbers behind the smithy. Three beasts are chained inside — they look like dogs the way a forge looks like a campfire. Their fur is patched with red, and where the patches are, the skin under them shines. They are not making noise. They are watching the door of their own shed, where you are standing.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb, '[]'::jsonb, 'never', 340),

('ember_outpost__kennel_sneak', 'ember_outpost', 'transition',
 $b$You move along the eastern wall of the shed where the wind carries your scent away from the chains. The hounds shift, but they do not lunge. You slip past them and out the back door of the kennel before the lead chain has stopped rattling. None of them barked. You'd rather they had, almost.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"avoided_kennel","value":true}}]$a$::jsonb,
 'never', 341),

('ember_outpost__kennel_fed', 'ember_outpost', 'transition',
 $b$You unwrap a strip of dried meat and toss it, slowly, with a flat hand. The first hound takes it without aggression. The second takes the second piece. The third looks at you for a long time, and then takes nothing — but it lies down, and it does not look at you again. You walk past them. None of them bark.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"consume_item","payload":{"item_id":"ration","qty":1}},{"kind":"set_flag","payload":{"key":"hounds_friendly","value":true}}]$a$::jsonb,
 'never', 342),

('ember_outpost__kennel_combat', 'ember_outpost', 'combat',
 $b$You move to draw, and the chains in the shed all rattle at once. The lead hound lunges before its chain has finished going taut, and the chain snaps, and the third hound is already moving.$b$,
 null, '{}'::jsonb, $t$["act_5", "combat"]$t$::jsonb,
 $a$[{"kind":"start_combat","payload":{"enemy_set_id":"fire_hounds"}}]$a$::jsonb,
 'never', 343),

-- Inner door
('ember_outpost__inner_door', 'ember_outpost', 'choice',
 $b$The inner door is a single slab of oak banded with iron, set in a stone arch. There is a lock-plate; there is a heavy bar on the inside (you can hear it when you press your ear); and somewhere along the eastern jamb, if Tyne told the truth, there is a hidden bolt that lifts the bar.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_5"]$t$::jsonb,
 '[]'::jsonb, 'pivotal_only', 350),

('ember_outpost__sanctum_calm', 'ember_outpost', 'transition',
 $b$You find the hidden bolt where Tyne said it would be — east jamb, two hands above the latch — and slide it. The bar inside the door rises with a soft thunk, and the door swings inward without sound. You step through into the keep proper.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"entered_keep_silent","value":true}}]$a$::jsonb,
 'never', 351),

('ember_outpost__sanctum_pick', 'ember_outpost', 'transition',
 $b$The lock is old and the picks you have are good enough. It takes you longer than it should because your hands are shaking, but it gives, and the door opens. Nothing in the keep stirs. Yet.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"entered_keep_silent","value":true}}]$a$::jsonb,
 'never', 352),

('ember_outpost__sanctum_alarm', 'ember_outpost', 'transition',
 $b$You break the door. You break it fast, and well, but you do not break it quietly. By the time the second hinge-pin has gone, a bell has begun to ring somewhere up in the keep — high, urgent, repeating. Voices answer it. You go through the doorway into the keep proper. The stair ahead is narrow and long.$b$,
 null, '{}'::jsonb, $t$["act_5"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"alarm_raised","value":true}}]$a$::jsonb,
 'never', 353),

-- ACT VI — Sanctum
('ember_outpost__sanctum_main', 'ember_outpost', 'scene',
 $b$The sanctum is smaller than you expected. A circular room of fitted stone, four braziers in the cardinal directions, a black iron stand at the centre, and on the stand the Smithlight — a small handheld lantern of dark bronze, the candle inside it burning steady against a draft you cannot feel. The room smells of nothing. Standing across the lantern from you, with one gloved hand resting on the stand, is a tall woman in red and black with her hood half down. Her face has Bren's eyes.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_6"]$t$::jsonb,
 '[]'::jsonb, 'pivotal_only', 400),

('ember_outpost__commander_dialog', 'ember_outpost', 'dialog',
 $b$"I've been trying to remember," the Commander says, before you have quite stopped moving, "whether I expected you. I think I did. Most of the people I expect don't come, and most of the ones who come, I didn't expect, so probably I am wrong about that too." She smiles, briefly, in a way that is not for you. "My name is Korr. There was an older name. I am told I was called Edda, but I don't remember being called that." She looks down at the lantern. "Tell me what you want from this room. Be specific. We can probably both have it, if you're specific."$b$,
 'Commander Korr',
 $sp$ {"tone":["intelligent","tired","not-cruel","convinced","reachable"], "default_mood":"open"} $sp$::jsonb,
 $t$["pivotal", "act_6"]$t$::jsonb, '[]'::jsonb, 'pivotal_only', 401),

('ember_outpost__korr_killed', 'ember_outpost', 'combat',
 $b$Korr's smile changes. She steps back from the lantern, draws — she is faster than you guessed — and the four braziers in the room flare at the same moment, like they had been waiting for it. The room is small enough that there is nowhere for either of you to go.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_6", "combat"]$t$::jsonb,
 $a$[{"kind":"start_combat","payload":{"boss_id":"commander_korr"}}]$a$::jsonb,
 'pivotal_only', 410),

('ember_outpost__korr_spared', 'ember_outpost', 'transition',
 $b$You tell Korr the things you know. You tell her the name. You tell her about Bren's hand. You tell her about Mira's husband. You tell her about the candle in Tarin's chapel that no longer keeps its flame. You do not raise your voice. You do not have to. After you have stopped speaking, Korr stands very still for a long time, and then she takes her hand off the lantern and turns away from it. "Take it," she says. "I am too tired to be the one to take it back." She walks past you and out of the sanctum without looking at you, and she does not call for help.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_6"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"korr_spared","value":true}},{"kind":"grant_item","payload":{"item_id":"the_smithlight","qty":1}}]$a$::jsonb,
 'pivotal_only', 411),

('ember_outpost__korr_convinced', 'ember_outpost', 'transition',
 $b$You speak — calmly, exactly, with the right kind of mercy — about what the Smithlight actually is, and what the Order has misunderstood about it. About the dwarf-priest and the smith four generations back. About the engraving in the dwarven chamber. Korr listens. At one point she closes her eyes and does not open them for a while. When she opens them she does not look like a Commander. She looks like a woman who has been asked, finally, the question she has been asking herself in private for years. She lifts the lantern and hands it to you herself.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_6"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"korr_convinced","value":true}},{"kind":"grant_item","payload":{"item_id":"the_smithlight","qty":1}}]$a$::jsonb,
 'pivotal_only', 412),

('ember_outpost__korr_betrayed', 'ember_outpost', 'transition',
 $b$You take the deal Korr is offering. You always knew you were going to. The Order has need of someone with your skill set, and the Commander has need of someone she can trust, and both of those are problems your face can solve. You do not take the lantern. You leave it on the iron stand. Korr touches your shoulder, briefly, on your way out. The touch is steady. The two of you do not need to say anything more.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_6"]$t$::jsonb,
 $a$[{"kind":"set_flag","payload":{"key":"korr_betrayed","value":true}}]$a$::jsonb,
 'pivotal_only', 413),

-- ACT VII — Endings
('ember_outpost__epilogue_hero', 'ember_outpost', 'outcome',
 $b$You walk back into Ashbrook with the Smithlight in your pack. Bren is in the door of the smithy when you come up the road; she sees the lantern before she sees you, and the look on her face is something you will keep. Tarin is on the chapel step, and when you hold the lantern out to him, he covers his eyes with one hand for longer than is dignified. The candle is lit again that same evening, from the lantern, in front of the entire village. It does not gutter. Nothing here does, for a while.

Mira's amulet, you give back to her in private. She holds it for a long time and then puts it around her own neck. "Thank you," she says, and it is the only thing either of you say.

Korr came home with you. She is staying with Bren now. The villagers are not sure how to feel about that. Neither is Bren. Both of them, together, are working it out.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_7", "ending"]$t$::jsonb,
 $a$[{"kind":"end_campaign","payload":{"outcome":"success","summary_seed":"You returned the Smithlight, and you brought Korr home. Ashbrook keeps its candle. The Order's brazier-carts will not be built, this season."}}]$a$::jsonb,
 'pivotal_only', 500),

('ember_outpost__epilogue_mercy', 'ember_outpost', 'outcome',
 $b$You walk back into Ashbrook with the Smithlight in your pack and Korr is not with you. Bren does not ask. You do not tell her, in any detail; it is between you and Korr now. The lantern goes back on its stand in the smithy that same afternoon. The candle in Tarin's chapel is lit from it that evening. It does not gutter.

What happened in the sanctum was a small thing and a large one. You let her live. You let her go. You will think about whether that was the right call for a long time. So will the village, when they finally piece the story together. They will not all come down on the same side. Bren, when you finally tell her, takes your hand for a moment without saying anything, and that is most of what you needed.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_7", "ending"]$t$::jsonb,
 $a$[{"kind":"end_campaign","payload":{"outcome":"success","summary_seed":"You spared Korr and brought the Smithlight home. The village got its candle back. Whether you did right by Korr is a question you and Ashbrook will keep arguing about."}}]$a$::jsonb,
 'pivotal_only', 501),

('ember_outpost__epilogue_pyrrhic', 'ember_outpost', 'outcome',
 $b$You come down off the bluff with the Smithlight wrapped in your cloak and a wound in your side that will scar wide. The fight in the sanctum was bad and you do not remember all of it. Korr is dead. The lantern is not.

Bren meets you on the road. She sees the lantern first. Then she looks at your hands. She does not say anything. She walks back to the smithy with you behind her, and she takes the lantern from your hands with both of hers and sets it on the rack above the forge, where it always lived. The candle in Tarin's chapel is lit that evening. It does not gutter.

Bren does not speak to you that day, or the next. On the third day she comes to the inn where you are staying, sits down across from you, and says, "Thank you. I am not all right. I am going to be. Thank you." Then she goes back to her smithy. You ride out of Ashbrook the next morning with most of what you came for, and a debt you will not be able to pay back to the only person who could forgive it.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_7", "ending"]$t$::jsonb,
 $a$[{"kind":"end_campaign","payload":{"outcome":"success","summary_seed":"You took the Smithlight back. Korr did not come home. The village's candle is lit; Bren is grieving; you are unsure whether you will be welcome again."}}]$a$::jsonb,
 'pivotal_only', 502),

('ember_outpost__epilogue_antihero', 'ember_outpost', 'outcome',
 $b$You stand on the parapet of the Ember Outpost beside Korr at sunset. The lantern is on the iron stand below, where you left it. The Order is yours now, in part — Korr is teaching you the rest. The smith's daughter you used to be hired by is going to find out, eventually, that you did not bring her sister home and did not bring the lantern home and are not coming home yourself.

You will see her in the field the day they march on Ashbrook the second time. You will be on the side that has the brazier-cart. She will be in front of the smithy holding her father's hammer. You don't know yet which of you flinches first. You have decided you will not be the one who flinches.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_7", "ending"]$t$::jsonb,
 $a$[{"kind":"end_campaign","payload":{"outcome":"failure","summary_seed":"You took Korr's deal. The Order has the Smithlight. Ashbrook is going to learn this the slow way, and you are going to be there to see it."}}]$a$::jsonb,
 'pivotal_only', 503),

('ember_outpost__epilogue_failure', 'ember_outpost', 'outcome',
 $b$The bell in the keep was the loudest thing you'd heard in months. By the time you got to the sanctum the room was already full of red leathers, and Korr was not in it, and the lantern was not in it either. You fought your way out down a stair you didn't remember climbing.

You woke up two days later in a barn three valleys south, with no memory of how you got there and most of your gear missing. The Smithlight is still in the Ember Outpost. Ashbrook is still smoking, in two columns, and Bren is still working small things at the forge, and Mira is still sitting on the step of the roofless house. You will go back, eventually. You are not going back today.$b$,
 null, '{}'::jsonb, $t$["pivotal", "act_7", "ending"]$t$::jsonb,
 $a$[{"kind":"end_campaign","payload":{"outcome":"failure","summary_seed":"The alarm beat you to the sanctum. You escaped without the Smithlight. Ashbrook is still waiting."}}]$a$::jsonb,
 'pivotal_only', 504)

on conflict (id) do nothing;


-- ---------------------------------------------------------------------
-- Edges — every transition in the graph.
-- ---------------------------------------------------------------------
-- Author convention for edge ids: "<from_node_id>:<option_id>"
-- ---------------------------------------------------------------------

insert into story_edges
  (id, from_node_id, option_id, option_label, to_node_id, requires, consumes, sort_order)
values

-- ACT I
('ember_outpost__intro:travel_dawn', 'ember_outpost__intro',
 'travel_dawn', 'Push on now and reach Ashbrook by morning',
 'ember_outpost__travel_dawn', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__intro:travel_dusk', 'ember_outpost__intro',
 'travel_dusk', 'Camp by the road and arrive at dusk',
 'ember_outpost__travel_dusk', '{}'::jsonb, '[]'::jsonb, 20),

('ember_outpost__travel_dawn:meet', 'ember_outpost__travel_dawn',
 'meet_traveler', 'Continue on the road',
 'ember_outpost__village_outskirts', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__travel_dusk:meet', 'ember_outpost__travel_dusk',
 'meet_traveler', 'Continue on the road',
 'ember_outpost__village_outskirts', '{}'::jsonb, '[]'::jsonb, 10),

('ember_outpost__village_outskirts:help', 'ember_outpost__village_outskirts',
 'help', 'Help the fleeing smith with rations',
 'ember_outpost__traveler_helped', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__village_outskirts:rob', 'ember_outpost__village_outskirts',
 'rob', 'Take what he is carrying',
 'ember_outpost__traveler_robbed', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__village_outskirts:press', 'ember_outpost__village_outskirts',
 'press', 'Let him pass and continue to Ashbrook',
 'ember_outpost__ashbrook_arrival', '{}'::jsonb, '[]'::jsonb, 30),

('ember_outpost__traveler_helped:on', 'ember_outpost__traveler_helped',
 'on', 'Press on into Ashbrook',
 'ember_outpost__ashbrook_arrival', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__traveler_robbed:on', 'ember_outpost__traveler_robbed',
 'on', 'Press on into Ashbrook',
 'ember_outpost__ashbrook_arrival', '{}'::jsonb, '[]'::jsonb, 10),

('ember_outpost__ashbrook_arrival:hub', 'ember_outpost__ashbrook_arrival',
 'enter_hub', 'Look around the village',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- ACT II hub
('ember_outpost__ashbrook_hub:inn', 'ember_outpost__ashbrook_hub',
 'visit_inn', 'Visit the inn',
 'ember_outpost__inn_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__ashbrook_hub:smith', 'ember_outpost__ashbrook_hub',
 'visit_smith', 'Visit Bren the smith',
 'ember_outpost__smith_dialog', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__ashbrook_hub:priest', 'ember_outpost__ashbrook_hub',
 'visit_priest', 'Visit Brother Tarin at the chapel',
 'ember_outpost__priest_dialog', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__ashbrook_hub:burnt', 'ember_outpost__ashbrook_hub',
 'visit_burnt_woman', 'Speak to the woman on the burnt step',
 'ember_outpost__burnt_woman_dialog', '{}'::jsonb, '[]'::jsonb, 40),
('ember_outpost__ashbrook_hub:orphan', 'ember_outpost__ashbrook_hub',
 'visit_orphan', 'Speak to the boy on the chapel wall',
 'ember_outpost__orphan_dialog', '{}'::jsonb, '[]'::jsonb, 50),
('ember_outpost__ashbrook_hub:stable', 'ember_outpost__ashbrook_hub',
 'visit_stable', 'Visit Old Hask at the stable',
 'ember_outpost__stable_dialog', '{}'::jsonb, '[]'::jsonb, 60),
('ember_outpost__ashbrook_hub:leave', 'ember_outpost__ashbrook_hub',
 'leave', 'Leave Ashbrook for the bluff',
 'ember_outpost__leave_for_outpost', '{}'::jsonb, '[]'::jsonb, 99),

-- Inn replies
('ember_outpost__inn_dialog:outpost', 'ember_outpost__inn_dialog',
 'ask_outpost', 'Ask about the Ember Outpost',
 'ember_outpost__inn_outpost_info', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__inn_dialog:korr', 'ember_outpost__inn_dialog',
 'ask_korr', 'Ask about the Commander',
 'ember_outpost__inn_korr_info', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__inn_dialog:drink', 'ember_outpost__inn_dialog',
 'drink', 'Take the drink',
 'ember_outpost__inn_drink', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__inn_dialog:room', 'ember_outpost__inn_dialog',
 'room', 'Take a room for the night',
 'ember_outpost__inn_room',
 '{"not_flag":["rested"]}'::jsonb, '[]'::jsonb, 40),
('ember_outpost__inn_dialog:leave', 'ember_outpost__inn_dialog',
 'leave', 'Leave the inn',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__inn_outpost_info:back', 'ember_outpost__inn_outpost_info',
 'back', 'Continue talking to Vela',
 'ember_outpost__inn_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__inn_korr_info:back', 'ember_outpost__inn_korr_info',
 'back', 'Continue talking to Vela',
 'ember_outpost__inn_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__inn_drink:back', 'ember_outpost__inn_drink',
 'back', 'Set the cup down',
 'ember_outpost__inn_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__inn_room:back', 'ember_outpost__inn_room',
 'back', 'Come back downstairs',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- Smith replies
('ember_outpost__smith_dialog:korr', 'ember_outpost__smith_dialog',
 'ask_korr', 'Ask about the Commander',
 'ember_outpost__smith_korr_info', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smith_dialog:help_anvil', 'ember_outpost__smith_dialog',
 'help_anvil', 'Take up the hammer for her',
 'ember_outpost__smith_anvil_help',
 '{"class":["blacksmith","warrior"],"stat":{"STR":">=12"}}'::jsonb,
 '[]'::jsonb, 20),
('ember_outpost__smith_dialog:repair', 'ember_outpost__smith_dialog',
 'repair', 'Pay her to repair your gear',
 'ember_outpost__smith_repair', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__smith_dialog:leave', 'ember_outpost__smith_dialog',
 'leave', 'Leave the smithy',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__smith_korr_info:back', 'ember_outpost__smith_korr_info',
 'back', 'Continue talking',
 'ember_outpost__smith_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smith_anvil_help:back', 'ember_outpost__smith_anvil_help',
 'back', 'Continue talking',
 'ember_outpost__smith_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smith_repair:back', 'ember_outpost__smith_repair',
 'back', 'Leave the smithy',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- Priest replies
('ember_outpost__priest_dialog:smithlight', 'ember_outpost__priest_dialog',
 'ask_smithlight', 'Ask about the Smithlight',
 'ember_outpost__priest_smithlight_info', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__priest_dialog:bless', 'ember_outpost__priest_dialog',
 'bless', 'Ask for a blessing',
 'ember_outpost__priest_blessing',
 '{"not_flag":["blessed"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__priest_dialog:pray', 'ember_outpost__priest_dialog',
 'pray', 'Sit and pray',
 'ember_outpost__priest_pray', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__priest_dialog:leave', 'ember_outpost__priest_dialog',
 'leave', 'Leave the chapel',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__priest_smithlight_info:back', 'ember_outpost__priest_smithlight_info',
 'back', 'Continue talking',
 'ember_outpost__priest_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__priest_blessing:back', 'ember_outpost__priest_blessing',
 'back', 'Step outside',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__priest_pray:back', 'ember_outpost__priest_pray',
 'back', 'Step outside',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- Burnt-house woman replies
('ember_outpost__burnt_woman_dialog:help', 'ember_outpost__burnt_woman_dialog',
 'help_rebuild', 'Help her clear and stack what is left',
 'ember_outpost__burnt_woman_helped',
 '{"stat":{"CON":">=12"}}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__burnt_woman_dialog:comfort', 'ember_outpost__burnt_woman_dialog',
 'comfort', 'Sit with her in silence',
 'ember_outpost__burnt_woman_comforted', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__burnt_woman_dialog:ask', 'ember_outpost__burnt_woman_dialog',
 'ask_attack', 'Ask her about the night of the attack',
 'ember_outpost__burnt_woman_info', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__burnt_woman_dialog:leave', 'ember_outpost__burnt_woman_dialog',
 'leave', 'Step away',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__burnt_woman_helped:back', 'ember_outpost__burnt_woman_helped',
 'back', 'Take the amulet and continue',
 'ember_outpost__ashbrook_hub', '[]'::jsonb, '[]'::jsonb, 10),
('ember_outpost__burnt_woman_comforted:back', 'ember_outpost__burnt_woman_comforted',
 'back', 'Step away',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__burnt_woman_info:back', 'ember_outpost__burnt_woman_info',
 'back', 'Step away',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- Orphan replies
('ember_outpost__orphan_dialog:feed', 'ember_outpost__orphan_dialog',
 'feed', 'Share your bread and cheese with him',
 'ember_outpost__orphan_fed', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__orphan_dialog:ask_dad', 'ember_outpost__orphan_dialog',
 'ask_dad', 'Ask about his father',
 'ember_outpost__orphan_father', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__orphan_dialog:play', 'ember_outpost__orphan_dialog',
 'play', 'Sit with him for a while',
 'ember_outpost__orphan_played', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__orphan_dialog:leave', 'ember_outpost__orphan_dialog',
 'leave', 'Move on',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__orphan_fed:back', 'ember_outpost__orphan_fed',
 'back', 'Move on',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__orphan_father:back', 'ember_outpost__orphan_father',
 'back', 'Move on',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__orphan_played:back', 'ember_outpost__orphan_played',
 'back', 'Move on',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 10),

-- Stable replies
('ember_outpost__stable_dialog:paths', 'ember_outpost__stable_dialog',
 'ask_paths', 'Ask about the paths up the bluff',
 'ember_outpost__stable_paths_info', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__stable_dialog:horses', 'ember_outpost__stable_dialog',
 'ask_horses', 'Ask about his lost horses',
 'ember_outpost__stable_horses', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__stable_dialog:leave', 'ember_outpost__stable_dialog',
 'leave', 'Leave the stable',
 'ember_outpost__ashbrook_hub', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__stable_paths_info:back', 'ember_outpost__stable_paths_info',
 'back', 'Continue talking',
 'ember_outpost__stable_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__stable_horses:back', 'ember_outpost__stable_horses',
 'back', 'Continue talking',
 'ember_outpost__stable_dialog', '{}'::jsonb, '[]'::jsonb, 10),

-- ACT III bridges
('ember_outpost__leave_for_outpost:view', 'ember_outpost__leave_for_outpost',
 'view', 'Climb the goat-track to look at the outpost',
 'ember_outpost__outpost_view', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__outpost_view:decide', 'ember_outpost__outpost_view',
 'decide', 'Decide your way in',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 10),

('ember_outpost__decide_approach:gate', 'ember_outpost__decide_approach',
 'gate', 'Walk up to the front gate openly',
 'ember_outpost__gate_approach', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__decide_approach:back', 'ember_outpost__decide_approach',
 'back_path', 'Climb the back of the bluff',
 'ember_outpost__back_path_climb',
 '{"flag":["knows_back_path"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__decide_approach:tunnel', 'ember_outpost__decide_approach',
 'smuggler', 'Find the smuggler Quint',
 'ember_outpost__smuggler_meet',
 '{"flag":["knows_smuggler_quint"]}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__decide_approach:dwarf', 'ember_outpost__decide_approach',
 'dwarven', 'Find a way down to the old dwarven workings',
 'ember_outpost__dwarf_tunnel',
 '{"class":["blacksmith"]}'::jsonb, '[]'::jsonb, 40),

-- Gate route
('ember_outpost__gate_approach:talk', 'ember_outpost__gate_approach',
 'talk', 'Talk to the watch sergeant',
 'ember_outpost__gate_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_approach:retreat', 'ember_outpost__gate_approach',
 'retreat', 'Withdraw and pick another way in',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 99),

('ember_outpost__gate_dialog:bribe', 'ember_outpost__gate_dialog',
 'bribe', 'Slip him a coin',
 'ember_outpost__gate_bribed', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_dialog:bluff', 'ember_outpost__gate_dialog',
 'bluff', 'Spin him a story',
 'ember_outpost__gate_bluffed',
 '{"stat":{"CHA":">=12"}}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__gate_dialog:intimidate', 'ember_outpost__gate_dialog',
 'intimidate', 'Stand a little too close',
 'ember_outpost__gate_intimidated',
 '{"class":["warrior"],"stat":{"STR":">=14"}}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__gate_dialog:fight', 'ember_outpost__gate_dialog',
 'fight', 'Draw on him',
 'ember_outpost__gate_combat', '{}'::jsonb, '[]'::jsonb, 40),
('ember_outpost__gate_dialog:retreat', 'ember_outpost__gate_dialog',
 'retreat', 'Pretend you wandered up by mistake',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 99),

('ember_outpost__gate_bribed:enter', 'ember_outpost__gate_bribed',
 'enter', 'Walk through the gate',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_bluffed:enter', 'ember_outpost__gate_bluffed',
 'enter', 'Walk through the gate',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_intimidated:enter', 'ember_outpost__gate_intimidated',
 'enter', 'Walk through the gate',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_combat:won', 'ember_outpost__gate_combat',
 'won', 'Step over the bodies and continue',
 'ember_outpost__gate_combat_won', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__gate_combat_won:enter', 'ember_outpost__gate_combat_won',
 'enter', 'Walk through the gate',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Back path
('ember_outpost__back_path_climb:careful', 'ember_outpost__back_path_climb',
 'careful', 'Climb carefully past the bad ledge',
 'ember_outpost__back_path_top',
 '{"stat":{"DEX":">=12"}}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__back_path_climb:rapid', 'ember_outpost__back_path_climb',
 'rapid', 'Climb fast and trust your hands',
 'ember_outpost__back_path_falter', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__back_path_climb:retreat', 'ember_outpost__back_path_climb',
 'retreat', 'Climb back down and try another way',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__back_path_falter:on', 'ember_outpost__back_path_falter',
 'on', 'Catch your breath and finish the climb',
 'ember_outpost__back_path_top', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__back_path_top:into', 'ember_outpost__back_path_top',
 'into', 'Slip into the courtyard',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Smuggler tunnel
('ember_outpost__smuggler_meet:pay', 'ember_outpost__smuggler_meet',
 'pay', 'Pay him in coin',
 'ember_outpost__smuggler_paid', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smuggler_meet:deal', 'ember_outpost__smuggler_meet',
 'deal', 'Tell him Jen sent you',
 'ember_outpost__smuggler_dealing',
 '{"flag":["orphan_friend"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__smuggler_meet:threaten', 'ember_outpost__smuggler_meet',
 'threaten', 'Make it clear he is not in your way',
 'ember_outpost__smuggler_threatened',
 '{"class":["warrior","rogue"]}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__smuggler_meet:leave', 'ember_outpost__smuggler_meet',
 'leave', 'Walk back the way you came',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__smuggler_paid:walk', 'ember_outpost__smuggler_paid',
 'walk', 'Step into the tunnel',
 'ember_outpost__tunnel_walk', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smuggler_dealing:walk', 'ember_outpost__smuggler_dealing',
 'walk', 'Step into the tunnel',
 'ember_outpost__tunnel_walk', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smuggler_threatened:walk', 'ember_outpost__smuggler_threatened',
 'walk', 'Step into the tunnel',
 'ember_outpost__tunnel_walk', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__tunnel_walk:exit', 'ember_outpost__tunnel_walk',
 'exit', 'Push the hatch open into the outpost',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Dwarven workings
('ember_outpost__dwarf_tunnel:song', 'ember_outpost__dwarf_tunnel',
 'song', 'Strike the iron fork the way a smith strikes iron',
 'ember_outpost__dwarf_tunnel_open',
 '{"class":["blacksmith"]}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__dwarf_tunnel:break', 'ember_outpost__dwarf_tunnel',
 'break', 'Break the seal with what tools you have',
 'ember_outpost__dwarf_tunnel_break', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__dwarf_tunnel:leave', 'ember_outpost__dwarf_tunnel',
 'leave', 'Climb back out and choose another way',
 'ember_outpost__decide_approach', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__dwarf_tunnel_open:through', 'ember_outpost__dwarf_tunnel_open',
 'through', 'Step through the open seal',
 'ember_outpost__forge_secret', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__dwarf_tunnel_break:through', 'ember_outpost__dwarf_tunnel_break',
 'through', 'Step through the broken seal',
 'ember_outpost__forge_secret', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__forge_secret:up', 'ember_outpost__forge_secret',
 'up', 'Take the back stair up into the outpost',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- ACT V courtyard hub
('ember_outpost__courtyard:barracks', 'ember_outpost__courtyard',
 'barracks', 'Approach the barracks',
 'ember_outpost__barracks_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__courtyard:chapel', 'ember_outpost__courtyard',
 'chapel', 'Approach the chapel of the ember',
 'ember_outpost__chapel_scene', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__courtyard:smithy', 'ember_outpost__courtyard',
 'smithy', 'Approach the smithy',
 'ember_outpost__smithy_scene', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__courtyard:kennel', 'ember_outpost__courtyard',
 'kennel', 'Approach the kennel',
 'ember_outpost__kennel_choice', '{}'::jsonb, '[]'::jsonb, 40),
('ember_outpost__courtyard:inner', 'ember_outpost__courtyard',
 'inner', 'Approach the inner door',
 'ember_outpost__inner_door', '{}'::jsonb, '[]'::jsonb, 50),

-- Barracks
('ember_outpost__barracks_dialog:pretend', 'ember_outpost__barracks_dialog',
 'pretend', 'Pretend to be a recruit on the supply detail',
 'ember_outpost__barracks_pass',
 '{"stat":{"CHA":">=10"}}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__barracks_dialog:attack', 'ember_outpost__barracks_dialog',
 'attack', 'Attack while they are still seated',
 'ember_outpost__barracks_combat', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__barracks_dialog:slip', 'ember_outpost__barracks_dialog',
 'slip', 'Back out of the doorway',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__barracks_pass:back', 'ember_outpost__barracks_pass',
 'back', 'Walk back into the courtyard',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__barracks_combat:back', 'ember_outpost__barracks_combat',
 'back', 'Wipe your blade and step out',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Chapel of the ember
('ember_outpost__chapel_scene:pray', 'ember_outpost__chapel_scene',
 'pray', 'Sit and try to pray as Tarin would',
 'ember_outpost__chapel_pray', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__chapel_scene:desecrate', 'ember_outpost__chapel_scene',
 'desecrate', 'Spit into the basin',
 'ember_outpost__chapel_desecrated', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__chapel_scene:search', 'ember_outpost__chapel_scene',
 'search', 'Search the room without disturbing the basin',
 'ember_outpost__chapel_clue', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__chapel_scene:leave', 'ember_outpost__chapel_scene',
 'leave', 'Step back outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__chapel_pray:back', 'ember_outpost__chapel_pray',
 'back', 'Stand and step outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__chapel_desecrated:back', 'ember_outpost__chapel_desecrated',
 'back', 'Step quickly outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__chapel_clue:back', 'ember_outpost__chapel_clue',
 'back', 'Step outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Smithy
('ember_outpost__smithy_scene:blueprints', 'ember_outpost__smithy_scene',
 'blueprints', 'Read the blueprints on the wall',
 'ember_outpost__smithy_blueprints', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smithy_scene:steal', 'ember_outpost__smithy_scene',
 'steal', 'Take a forge-pick and files',
 'ember_outpost__smithy_steal', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__smithy_scene:apprentice', 'ember_outpost__smithy_scene',
 'apprentice', 'Speak to the boy on the bellows',
 'ember_outpost__smithy_apprentice_dialog', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__smithy_scene:leave', 'ember_outpost__smithy_scene',
 'leave', 'Step back outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__smithy_blueprints:back', 'ember_outpost__smithy_blueprints',
 'back', 'Continue looking around the smithy',
 'ember_outpost__smithy_scene', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smithy_steal:back', 'ember_outpost__smithy_steal',
 'back', 'Step back outside',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Apprentice
('ember_outpost__smithy_apprentice_dialog:befriend', 'ember_outpost__smithy_apprentice_dialog',
 'befriend', 'Show him Bren''s hammer',
 'ember_outpost__apprentice_friend',
 '{"flag":["forge_friend"]}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__smithy_apprentice_dialog:silence', 'ember_outpost__smithy_apprentice_dialog',
 'silence', 'Make sure he will not call out',
 'ember_outpost__apprentice_silenced', '{}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__smithy_apprentice_dialog:leave', 'ember_outpost__smithy_apprentice_dialog',
 'leave', 'Step away',
 'ember_outpost__smithy_scene', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__apprentice_friend:back', 'ember_outpost__apprentice_friend',
 'back', 'Continue exploring',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__apprentice_silenced:back', 'ember_outpost__apprentice_silenced',
 'back', 'Walk on',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Kennel
('ember_outpost__kennel_choice:sneak', 'ember_outpost__kennel_choice',
 'sneak', 'Move along the wall and out the back door',
 'ember_outpost__kennel_sneak',
 '{"stat":{"DEX":">=12"}}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__kennel_choice:feed', 'ember_outpost__kennel_choice',
 'feed', 'Toss them dried meat',
 'ember_outpost__kennel_fed',
 '{"item":["ration"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__kennel_choice:fight', 'ember_outpost__kennel_choice',
 'fight', 'Draw and finish them',
 'ember_outpost__kennel_combat', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__kennel_choice:retreat', 'ember_outpost__kennel_choice',
 'retreat', 'Step back from the kennel door',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__kennel_sneak:back', 'ember_outpost__kennel_sneak',
 'back', 'Continue around the keep',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__kennel_fed:back', 'ember_outpost__kennel_fed',
 'back', 'Continue around the keep',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__kennel_combat:back', 'ember_outpost__kennel_combat',
 'back', 'Step out of the shed',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 10),

-- Inner door
('ember_outpost__inner_door:bolt', 'ember_outpost__inner_door',
 'bolt', 'Use the hidden bolt on the eastern jamb',
 'ember_outpost__sanctum_calm',
 '{"flag":["apprentice_help"]}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__inner_door:pick', 'ember_outpost__inner_door',
 'pick', 'Pick the lock',
 'ember_outpost__sanctum_pick',
 '{"item":["bent_lockpick","forge_pick"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__inner_door:break', 'ember_outpost__inner_door',
 'break', 'Break the door',
 'ember_outpost__sanctum_alarm', '{}'::jsonb, '[]'::jsonb, 30),
('ember_outpost__inner_door:retreat', 'ember_outpost__inner_door',
 'retreat', 'Withdraw and try something else first',
 'ember_outpost__courtyard', '{}'::jsonb, '[]'::jsonb, 99),
('ember_outpost__sanctum_calm:up', 'ember_outpost__sanctum_calm',
 'up', 'Climb the stair into the keep',
 'ember_outpost__sanctum_main', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__sanctum_pick:up', 'ember_outpost__sanctum_pick',
 'up', 'Climb the stair into the keep',
 'ember_outpost__sanctum_main', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__sanctum_alarm:up', 'ember_outpost__sanctum_alarm',
 'up', 'Climb the stair into the keep',
 'ember_outpost__sanctum_main', '{}'::jsonb, '[]'::jsonb, 10),

-- ACT VI sanctum + Korr
('ember_outpost__sanctum_main:talk', 'ember_outpost__sanctum_main',
 'talk', 'Speak to her',
 'ember_outpost__commander_dialog', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__sanctum_main:strike', 'ember_outpost__sanctum_main',
 'strike', 'Draw without speaking',
 'ember_outpost__korr_killed', '{}'::jsonb, '[]'::jsonb, 20),

('ember_outpost__commander_dialog:kill', 'ember_outpost__commander_dialog',
 'kill', 'Refuse her offer and draw',
 'ember_outpost__korr_killed', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__commander_dialog:spare',
 'ember_outpost__commander_dialog', 'spare',
 'Tell her the things you know about her sister',
 'ember_outpost__korr_spared',
 '{"flag":["knows_korr_sister","knows_korr_real_name"]}'::jsonb,
 '[]'::jsonb, 20),
('ember_outpost__commander_dialog:convince',
 'ember_outpost__commander_dialog', 'convince',
 'Tell her what the Smithlight actually is',
 'ember_outpost__korr_convinced',
 '{"flag":["knows_relic","knows_smithlight_origin"]}'::jsonb,
 '[]'::jsonb, 30),
('ember_outpost__commander_dialog:betray',
 'ember_outpost__commander_dialog', 'betray',
 'Take the deal she is offering',
 'ember_outpost__korr_betrayed',
 '{"stat":{"CHA":">=12"}}'::jsonb, '[]'::jsonb, 40),

('ember_outpost__korr_killed:to_pyrrhic', 'ember_outpost__korr_killed',
 'on', 'Take the lantern and walk out',
 'ember_outpost__epilogue_pyrrhic', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__korr_spared:to_mercy', 'ember_outpost__korr_spared',
 'on', 'Take the lantern and walk out',
 'ember_outpost__epilogue_mercy', '{}'::jsonb,
 '[{"kind":"set_flag","payload":{"key":"chose_mercy","value":true}}]'::jsonb, 10),
('ember_outpost__korr_spared:to_hero', 'ember_outpost__korr_spared',
 'with_korr', 'Walk out with Korr',
 'ember_outpost__epilogue_hero',
 '{"flag":["mira_grateful","apprentice_help"]}'::jsonb, '[]'::jsonb, 20),
('ember_outpost__korr_convinced:to_hero', 'ember_outpost__korr_convinced',
 'on', 'Take the lantern and walk out with her at your side',
 'ember_outpost__epilogue_hero', '{}'::jsonb, '[]'::jsonb, 10),
('ember_outpost__korr_betrayed:to_anti', 'ember_outpost__korr_betrayed',
 'on', 'Walk out into the keep at her side',
 'ember_outpost__epilogue_antihero', '{}'::jsonb, '[]'::jsonb, 10),

-- Failure escape route — if alarm raised AND no allies, exit via failure
('ember_outpost__sanctum_alarm:flee', 'ember_outpost__sanctum_alarm',
 'flee', 'Turn back and run before the keep closes on you',
 'ember_outpost__epilogue_failure', '{}'::jsonb, '[]'::jsonb, 99)

on conflict (id) do nothing;


-- ---------------------------------------------------------------------
-- Wire root
-- ---------------------------------------------------------------------
update story_templates
   set root_node_id = 'ember_outpost__intro'
 where id = 'ember_outpost';
